version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pos_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos_frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:5173"  # maps Vite dev server
    depends_on:
      - backend

volumes:
  db_data:
